# coding=utf-8
# Solution to problem 45
# Problem Statement: Triangular, pentagonal, and hexagonal
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle
#  
# Tn=n(n+1)/2
#  
# 1, 3, 6, 10, 15, ...
# Pentagonal
#  
# Pn=n(3n−1)/2
#  
# 1, 5, 12, 22, 35, ...
# Hexagonal
#  
# Hn=n(2n−1)
#  
# 1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.
#


def is_pentagonal(n):
    return (((1 + 24 * n) ** 0.5) + 1) % 6 == 0


def tph():
    i = 143
    while 1:
        i += 1
        ans = i * (2 * i - 1)
        if is_pentagonal(ans):
            return ans


if __name__ == "__main__":
    print tph()
